version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11   
    commands:
      - echo "Pulando instalação de dependências"

  build:
    commands:
      - echo "Zipando src/ para lambda_package.zip"
      - cd src
      - zip -r ../lambda_package.zip .

  post_build:
    commands:
      - echo ">> LAMBDA_FUNCTION_NAME='$LAMBDA_FUNCTION_NAME'"
      - set -x  
      - aws lambda update-function-code \
          --function-name "$LAMBDA_FUNCTION_NAME" \
          --zip-file fileb://lambda_package.zip \
          --region us-east-1


artifacts:
  files:
    - lambda_package.zip
