version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11   
    commands:
      - echo "Pulando instalação de dependências"

  
  build:
  commands:
    - echo "Zipando src/ para lambda_package.zip"
    - cd src
    - zip -r ../lambda_package.zip .
    - cd ..



  post_build:
  commands:
    - echo "Verificando existência de lambda_package.zip"
    - ls -l lambda_package.zip
    - echo "Atualizando função Lambda: $LAMBDA_FUNCTION_NAME"
    - aws lambda update-function-code --function-name "$LAMBDA_FUNCTION_NAME" --zip-file fileb://lambda_package.zip --region us-east-1


artifacts:
  files:
    - lambda_package.zip
