version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - set -e
      - echo "==> Limpando pastas anteriores"
      - rm -rf lambda_package.zip python.zip layer python

  build:
    commands:
      - set -e
      - echo "==> Instalando dependências para a layer"
      - mkdir -p layer/python
      - pip install -r src/lambda/requirements.txt -t layer/python
      - echo "==> Empacotando a layer"
      - cd layer/python
      - zip -r ../../python.zip .
      - cd ../..
      - ls -lh
      - echo "==> Empacotando o código da Lambda"
      - cd src/lambda
      - zip -r ../../lambda_package.zip . 
      - cd ../..
      - ls -lh  


  post_build:
    commands:
      - set -e
      - ls -lh
      - echo "==> Enviando ZIP da layer para o S3"
      - aws s3 cp python.zip s3://$LAYER_BUCKET/layers/python.zip --region $AWS_REGION
      - echo "==> Publicando nova versão da layer usando S3"
      - export LAYER_RESULT=$(aws lambda publish-layer-version --layer-name $LAYER_NAME --content S3Bucket=$LAYER_BUCKET,S3Key=layers/python.zip --compatible-runtimes python3.11 --region $AWS_REGION)
      - echo "$LAYER_RESULT"
      - export LAYER_VERSION=$(echo "$LAYER_RESULT" | python3 -c 'import sys, json; print(json.load(sys.stdin)["Version"])')
      - export LAYER_ARN="arn:aws:lambda:${AWS_REGION}:${AWS_ACCOUNT_ID}:layer:${LAYER_NAME}:${LAYER_VERSION}"
      - echo "ARN da layer ==> $LAYER_ARN"
      - echo "==> Atualizando configuração da função Lambda para usar a nova layer"
      - aws lambda update-function-configuration --function-name $LAMBDA_FUNCTION_NAME --layers $LAYER_ARN --region $AWS_REGION
      - echo "==> Atualizando código da função Lambda"
      - n=0; until aws lambda update-function-code --function-name $LAMBDA_FUNCTION_NAME --zip-file fileb://lambda_package.zip --region $AWS_REGION || [ $n -ge 5 ]; do echo "Retrying update... ($n)"; n=$((n+1)); sleep 10; done; [ $n -lt 5 ] || { echo "Falha ao atualizar código da Lambda após múltiplas tentativas"; exit 1; }

artifacts:
  files:
    - lambda_package.zip
    - python.zip
